version: '3.8'

services:
  rancher:
    image: rancher:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    privileged: true
    ports:
      - ${APP_HTTP_PORT}:80
      - ${APP_HTTPS_PORT}:443
    restart: always
    user: root
    stdin_open: true
    tty: true

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  rancher: